video:
  size: [ 640,480 ]
LKAS:
  lanes_detection:
    region_of_interest:
      - [ 75,480 ]
      - [ 565,480 ]
      - [ 400,300 ]
      - [ 200,300 ]
    gaussian_blur: # noise reduction frame
      kernel_size: [ 5,5 ]
      deviation: 0
    threshold: # convert image to dark and white pixels using adaptiveThreshold
      block_size: 3
      constant: 2
    canny: # identifies edges/ lines comparing contrast
      low_threshold: 50
      high_threshold: 150
    lines_hough_transform: # detects lines using houghTransformP
      rho: 2
      thetha: 0.01745329251 # ( pi/180)
      threshold: 40 # minimum points required to intersect to describe a line
      min_line_length: 25 # px
      max_line_gap: 70 #px
