video:
  size: [ 640,480 ]
  track_width: 35cm=0.35/ 50-600
  dashed_markings: 4.5cm=0.045/ 426-462
  y_meters_per_pixel: 0.00063636363 # 35cm in 550px
  x_meters_per_pixel: 0.00125
LKAS:
  lanes_detection:
    region_of_interest:
      - [ 100,200 ] #upperleft
      - [ 600,200 ] #upperright
      - [ 639,479 ] #lowerright
      - [ 0,479 ] #lowerleft
    gaussian_blur: # noise reduction frame
      active: true
      kernel_size: [ 5,5 ]
      deviation: 0
    threshold: # convert image to dark and white pixels using adaptiveThreshold
      active: true
      adaptive: false
      threshold: 150 # min pixel intensity to be considered white
      block_size: 3 # for adaptive threshold
      constant: 2 # for adaptive threshold
    canny: # identifies edges/ lines comparing contrast
      low_threshold: 50
      high_threshold: 150
    lines_hough_transform: # detects lines using houghTransformP
      rho: 2
      thetha: 0.01745329251 # ( pi/180)
      threshold: 40 # minimum points required to intersect to describe a line
      min_line_length: 10 # px
      max_line_gap: 70 #px
    warp_perspective:
      src:
        - [ 100,200 ] #upperleft
        - [ 600,200 ] #upperright
        - [ 0,479 ] #lowerleft
        - [ 639,479 ] #lowerright
      dst:
        - [ 0, 0 ]
        - [ 639, 0 ]
        - [ 0, 479 ]
        - [ 639, 479 ]
    colour_filtering:
      active: false
      lower_white: [ 0, 160, 10 ] #HLS
      upper_white: [ 255, 255, 255 ] #HLS